apiVersion: v2
name: docker-registry-pull-cache
description: "Docker registry set as pull through cache"
type: application
version: 0.15.2
appVersion: 2.8.1
dependencies:
  - name: common
    repository: https://szpadel.github.io/library-charts
    version: 0.19.2
maintainers:
  - name: Szpadel
    email: piotrekrogowski@gmail.com
sources:
  - https://github.com/Szpadel/public-charts/tree/master/charts/docker-registry-pull-cache
  - https://github.com/Szpadel/public-charts/tree/master/containers/cleanup-registry-cache
