image:
  repository: registry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


additionalControllers:
  cleanup:
    enabled: true
    type: cronjob
    schedule: "0 0 * * *"
    env:
      REGISTRY_URL: 'http://{{ include "common.names.fullname" . }}:5000'
    image:
      repository: ghcr.io/szpadel/cleanup-registry-cache
      pullPolicy: IfNotPresent
      tag: 0.1.0
    persistence:
      registry:
        enabled: false

env:
  CLEANUP_OLDER_THAN_DAYS: 30
  REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
  REGISTRY_STORAGE_DELETE_ENABLED: "true"

service:
  main:
    ports:
      http:
        port: 5000

ingress:
  main:
    enabled: false

persistence:
  registry:
    enabled: true
    accessMode: ReadWriteOnce
    type: pvc
    size: 50Gi
    mountPath: /var/lib/registry
