image:
  repository: registry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
  REGISTRY_STORAGE_DELETE_ENABLED: "true"

service:
  main:
    ports:
      http:
        port: 5000

ingress:
  main:
    enabled: false

persistence:
  registry:
    enabled: true
    accessMode: ReadWriteOnce
    type: pvc
    size: 50Gi
    mountPath: /var/lib/registry
