apiVersion: v2
name: repman
homeURL: https://repman.io
description: "Repman - PHP Repository Manager: packagist proxy and host for private packages"
type: application
version: 3.0.0
appVersion: 1.4.0
dependencies:
  - name: minio
    version: 12.1.10
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: common
    repository: https://szpadel.github.io/library-charts
    version: 0.2.0
maintainers:
  - name: Szpadel
    email: piotrekrogowski@gmail.com
sources:
  - https://github.com/Szpadel/public-charts/tree/master/charts/repman
  - https://github.com/repman-io/repman
