apiVersion: v2
name: repman
homeURL: https://repman.io
description: "Repman - PHP Repository Manager: packagist proxy and host for private packages"
type: application
version: 1.0.0
appVersion: 1.2.0-dev
prerelease: true
dependencies:
  - name: minio
    version: 8.0.9
    repository: https://helm.min.io/
    condition: config.minio.enabled
  - name: postgresql
    version: 10.2.1
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Szpadel
    email: piotrekrogowski@gmail.com
