apiVersion: v2
name: repman
homeURL: https://repman.io
description: "Repman - PHP Repository Manager: packagist proxy and host for private packages"
type: application
version: 3.2.0
# renovate: image=buddy/repman
appVersion: 1.4.0
dependencies:
  - name: minio
    version: 12.2.6
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: common
    repository: https://szpadel.github.io/library-charts
    version: 0.6.2
  - name: redis
    version: 17.9.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
maintainers:
  - name: Szpadel
    email: piotrekrogowski@gmail.com
sources:
  - https://github.com/Szpadel/public-charts/tree/master/charts/repman
  - https://github.com/repman-io/repman
