apiVersion: v2
name: repman
homeURL: https://repman.io
description: "Repman - PHP Repository Manager: packagist proxy and host for private packages"
type: application
version: 1.1.3
appVersion: 1.2.2
prerelease: true
dependencies:
  - name: minio
    version: 8.0.9
    repository: https://helm.min.io/
    condition: config.minio.enabled
  - name: postgresql
    version: 10.2.1
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Szpadel
    email: piotrekrogowski@gmail.com
sources:
  - https://github.com/Szpadel/public-charts/tree/master/charts/repman
  - https://github.com/repman-io/repman
