image:
  repository: ghcr.io/szpadel/cleanup-registry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  main:
    ports:
      http:
        port: 8081

ingress:
  main:
    enabled: false
