apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "repman.fullname" . }}-general
  labels:
    {{- include "repman.labels" . | nindent 4 }}
data:
  APP_HOST: {{ .Values.config.defaultHostname | quote }}
  APP_URL_SCHEME: {{ .Values.config.scheme | quote }}
  APP_ALLOWED_PACKAGE_TYPES: {{ .Values.config.allowedPackageTypes | quote }}
  APP_GITLAB_API_URL: {{ .Values.config.gitlabApiUrl | quote }}
  APP_ENV: prod
  APP_DEBUG: "0"
  APP_SECRET: {{ .Values.config.secret }}
  MESSENGER_TRANSPORT_DSN: doctrine://default
  EWZ_RECAPTCHA_ENABLED: "false"
  EWZ_RECAPTCHA_SITE_KEY: none
  EWZ_RECAPTCHA_SECRET: none
  PROXY_DIST_DIR: var/proxy
  PACKAGES_DIST_DIR: var/repo
  SECURITY_ADVISORIES_DB_DIR: var/security-advisories
  STORAGE_SOURCE: storage.s3
  STORAGE_AWS_OPAQUE_AUTH: "true"
  TRUSTED_PROXIES: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
