apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "repman.fullname" . }}
  labels:
    {{- include "repman.www.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  {{- if not .Values.repman.autoscaling.enabled }}
  replicas: {{ .Values.repman.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "repman.www.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config_files: {{ include (print $.Template.BasePath "/configmap_files.yaml") . | sha256sum }}
        checksum/config_general: {{ include (print $.Template.BasePath "/configmap_general.yaml") . | sha256sum }}
      labels:
        {{- include "repman.www.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-copy-public
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.repman.image.repository }}:{{ .Values.repman.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.repman.image.pullPolicy }}
          command: [ 'sh', '-c', 'cp -Rf /app/public /mnt' ]
          volumeMounts:
            - name: public
              mountPath: /mnt/public
          resources:
            {{- toYaml .Values.repman.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-setup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.repman.image.repository }}:{{ .Values.repman.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.repman.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              bin/console d:m:m --no-interaction &&
              bin/console messenger:setup-transports --no-interaction &&
              bin/console assets:install
          env:
            {{- include "repman.database.credentials.env" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "repman.fullname" . }}-general
            - prefix: MAILER_
              secretRef:
                {{- if .Values.config.mailer.existingSecret }}
                name: {{ .Values.config.mailer.existingSecret | quote }}
                {{- else }}
                name: {{ include "repman.fullname" . }}-mailer
                {{- end }}
            - prefix: OAUTH_
              secretRef:
                {{- if .Values.config.oauth.existingSecret }}
                name: {{ .Values.config.oauth.existingSecret | quote }}
                {{- else }}
                name: {{ include "repman.fullname" . }}-oauth
                {{- end }}
            - prefix: STORAGE_AWS_
              secretRef:
                {{- if ( and .Values.config.externalS3.existingSecret .Values.config.externalS3.enabled) }}
                name: {{ .Values.config.externalS3.existingSecret | quote }}
                {{- else }}
                name: {{ include "repman.fullname" . }}-s3
                {{- end }}
          volumeMounts:
            - name: files
              mountPath: /app/config/services_prod.yaml
              subPath: services_prod_yaml
              readOnly: true
            - name: files
              mountPath: /app/src/Migrations/Version20210115094614.php
              subPath: Version20210115094614_php
              readOnly: true
            - name: public
              mountPath: /app/public
          resources:
            {{- toYaml .Values.repman.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}-repman
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.repman.image.repository }}:{{ .Values.repman.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.repman.image.pullPolicy }}
          env:
            {{- include "repman.database.credentials.env" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "repman.fullname" . }}-general
            - prefix: MAILER_
              secretRef:
                {{- if .Values.config.mailer.existingSecret }}
                name: {{ .Values.config.mailer.existingSecret | quote }}
                {{- else }}
                name: {{ include "repman.fullname" . }}-mailer
                {{- end }}
            - prefix: OAUTH_
              secretRef:
                {{- if .Values.config.oauth.existingSecret }}
                name: {{ .Values.config.oauth.existingSecret | quote }}
                {{- else }}
                name: {{ include "repman.fullname" . }}-oauth
                {{- end }}
            - prefix: STORAGE_AWS_
              secretRef:
                {{- if ( and .Values.config.externalS3.existingSecret .Values.config.externalS3.enabled) }}
                name: {{ .Values.config.externalS3.existingSecret | quote }}
                {{- else }}
                name: {{ include "repman.fullname" . }}-s3
                {{- end }}
          volumeMounts:
            - name: files
              mountPath: /app/config/services_prod.yaml
              subPath: services_prod_yaml
              readOnly: true
          resources:
            {{- toYaml .Values.repman.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - name: files
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx_conf
              readOnly: true
            - name: public
              mountPath: /app/public
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            timeoutSeconds: 10
            httpGet:
              path: /login
              port: http
          readinessProbe:
            httpGet:
              path: /login
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: files
          configMap:
            name: {{ include "repman.fullname" . }}-files
        - name: public
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
