{{- if .Values.repman.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "repman.fullname" . }}
  labels:
    {{- include "repman.www.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "repman.fullname" . }}
  minReplicas: {{ .Values.repman.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.repman.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.repman.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ .Values.repman.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.repman.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.repman.autoscaling.targetMemory }}
    {{- end }}
{{- end }}
