{{- if not .Values.config.mailer.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repman.fullname" . }}-mailer
  labels:
    {{- include "repman.labels" . | nindent 4 }}
data:
  DSN: {{ .Values.config.mailer.dsn | b64enc | quote }}
  SENDER: {{ .Values.config.mailer.sender | b64enc | quote }}
{{- end }}
