{{- if not .Values.config.oauth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repman.fullname" . }}-oauth
  labels:
    {{- include "repman.labels" . | nindent 4 }}
data:
  GITHUB_CLIENT_ID: {{ .Values.config.oauth.github.id | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.config.oauth.github.secret | b64enc | quote }}
  GITLAB_CLIENT_ID: {{ .Values.config.oauth.gitlab.id | b64enc | quote }}
  GITLAB_CLIENT_SECRET: {{ .Values.config.oauth.gitlab.secret | b64enc | quote }}
  BITBUCKET_CLIENT_ID: {{ .Values.config.oauth.bitbucket.id | b64enc | quote }}
  BITBUCKET_CLIENT_SECRET: {{ .Values.config.oauth.bitbucket.secret | b64enc | quote }}
  BUDDY_CLIENT_ID: {{ .Values.config.oauth.buddy.id | b64enc | quote }}
  BUDDY_CLIENT_SECRET: {{ .Values.config.oauth.buddy.secret | b64enc | quote }}
{{- end }}
