{{- if (or (not .Values.config.externalS3.existingSecret) (not .Values.config.externalS3.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repman.fullname" . }}-s3
  labels:
    {{- include "repman.labels" . | nindent 4 }}
data:
{{- if .Values.config.externalS3.enabled }}
  BUCKET: {{ .Values.config.externalS3.bucket | b64enc | quote }}
  REGION: {{ .Values.config.externalS3.region | b64enc | quote }}
  KEY: {{ .Values.config.externalS3.key | b64enc | quote }}
  SECRET: {{ .Values.config.externalS3.secret | b64enc | quote }}
{{- else }}
  BUCKET: {{ .Values.minio.defaultBucket.name | b64enc | quote }}
  REGION: {{ "us-east-1" | b64enc | quote }}
  KEY: {{ .Values.minio.accessKey | b64enc | quote }}
  SECRET: {{ .Values.minio.secretKey | b64enc | quote }}
  PATH_STYLE_ENDPOINT: {{ "true" | b64enc | quote }}
  ENDPOINT: {{ (printf "http://%s-%s.%s:9000" (include "repman.fullname" .) ("minio") (.Release.Namespace) ) | b64enc | quote }}
{{- end }}
{{- end }}
