image:
  # -- image repository
  # USE docker.seadrive.org/seafileltd/seafile-pro-mc for pro
  repository: seafileltd/seafile-mc
  # -- image tag
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

seafile:
  pro: false
  admin_email: example@example.com
  admin_initial_password: adminpassword123

# Required for pro
imagePullSecrets: []

# -- environment variables. See more environment variables in the [seafile documentation](https://manual.seafile.com/).
# @default -- See below
env:
  # -- Set the container timezone
  TIME_ZONE: Etc/UTC
  # -- The hostname of your database
  DB_HOST: "{{ printf \"%s-mysql\" (.Release.Name) }}"
  # -- The root password for mysql (used for initial setup)
  DB_ROOT_PASSWD: "{{ .Values.mariadb.auth.rootPassword }}"
  # -- The initial admin user's email
  SEAFILE_ADMIN_EMAIL: "{{ .Values.seafile.admin_email }}"
  # -- The initial admin user's password
  SEAFILE_ADMIN_PASSWORD: "{{ .Values.seafile.admin_initial_password }}"
  # -- The hostname for the server (set to your ingress hostname)
  SEAFILE_SERVER_HOSTNAME: "https://{{ if .Values.ingress }}{{ if .Values.ingress.main.enabled }}{{ ( index .Values.ingress.main.hosts 0 ).host }}{{ else }}example.com{{ end }}{{ else }}example.com{{ end }}"
  SEAFILE_SERVER_LETSENCRYPT: false

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- See values.yaml
mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: seafile
    username: seafile
    password: seafilepass
    rootPassword: seafilerootpass
  primary:
    persistence:
      enabled: true
      # storageClass: ""

persistence:
  data:
    enabled: false
    mountPath: /shared

memcached:
  enabled: true

elasticsearch:
  enabled: false
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    enabled: false
  volumePermissions:
    enabled: true
