name: Build and Push Docker Containers

on:
  push:
    paths:
      - 'containers/**'
    branches:
      - master
  pull_request:
    paths:
      - 'containers/**'

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Matrix
        id: set-matrix
        run: |
          DIFF=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} -- containers ||
            git diff --name-status HEAD~1 ${{ github.sha }} -- containers)
          # grep -v '^D' # do not rebuild when image is deleted
          # awk '{if ($3 != "") print $3; else print $2}' # Handle cases files where renamed
          # awk -F/ '{print $2}' # Extract image name from path
          containers=$(echo "$DIFF" | grep -v '^D' | awk '{if ($3 != "") print $3; else print $2}' | awk -F/ '{print $2}' | sort -u)
          matrix=$(echo $containers | tr ' ' '\n' | jq -R . | jq -rs '{"container_path": .} | @json')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT


  build_and_push:
    if: ${{fromJson(needs.prepare_matrix.outputs.matrix).container_path}}
    needs: prepare_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_path: ${{fromJson(needs.prepare_matrix.outputs.matrix).container_path}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set environment variables
        run: |
          echo "PUSH_IMAGE=false" >> $GITHUB_ENV
          if [[ ${{ github.event_name }} == "push" && ${{ github.ref }} == "refs/heads/master" ]]; then
            echo "PUSH_IMAGE=true" >> $GITHUB_ENV
          fi
          REPOSITORY_OWNER=${{ github.repository_owner }}
          echo "REPOSITORY_OWNER=${REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        if: env.PUSH_IMAGE == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test Docker image
        run: |
          cd containers/${{ matrix.container_path }}
          version=$(cat VERSION)
          image_name="ghcr.io/$REPOSITORY_OWNER/${{ matrix.container_path }}:${version}"
          docker buildx build --load --tag "${image_name}" .

      - name: Push Docker image
        if: env.PUSH_IMAGE == 'true'
        run: |
          cd containers/${{ matrix.container_path }}
          version=$(cat VERSION)
          image_name="ghcr.io/$REPOSITORY_OWNER/${{ matrix.container_path }}:${version}"
          docker buildx build --push --tag "${image_name}" .
